name: Leap
targets:
  Leap:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources: [Leap]
    info:
      path: ./Info.plist
      version: 0.1.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
      - carthage: AnyCodable